core/src/main/java/org/pentaho/platform/scheduler2/quartz/EmbeddedQuartzSystemListener.java
That it may be overridden in the EE implementation.
Necessary for https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/47
=> [BACKLOG-38076] Introduce initializeScheduler() method 

ui/src/main/java/org/pentaho/mantle/client/workspace/JsJob.java, ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
- Also, changes `JsJob.getOutputPath()` to account for the new syntax of generic file paths
JIRA issue: https://hv-eng.atlassian.net/browse/BACKLOG-37877
Merge along with:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1003
@pentaho/hoth, please, review.
=> [BACKLOG-37877] Scheduler perspective only shows hyperlink to repo output locations

assembly/src/main/plugin.spring.xml, core/jmeter.properties, core/scheduler-plugin-biserver-schedule-jmeter.jmx, core/src/main/java/org/pentaho/platform/scheduler2/ISchedulerOutputPathResolver.java, core/src/main/java/org/pentaho/platform/scheduler2/action/ActionRunner.java, core/src/main/java/org/pentaho/platform/scheduler2/action/SchedulerOutputPathResolver.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/services/ISchedulerServicePlugin.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, core/src/test/java/org/pentaho/platform/scheduler2/action/ActionRunnerTest.java, core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java
[[CLEANUP] ported jmeter tests and updated from BA 5.X to 10.1 rest urls](https://github.com/pentaho/pentaho-scheduler-plugin/pull/60/commits/9aceab9e47cbb4928d58a1e9b712a4a01b8b73aa)
[[BACKLOG-37872][BACKLOG-38317] Backend Write to VFS location, Create …](https://github.com/pentaho/pentaho-scheduler-plugin/pull/60/commits/223802766d389eccdd3e76d6614bf03c1b625a3c) 
…PVFS implementation for RepositoryFileStreamProvider
- add interface ISchedulerServicePlugin to SchedulerResource
- allow for different implemeantion for related scheduling functionality
**NOTE** ** I wold like to keep these two commits separate***
relates to EE version PR:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/75
[BACKLOG-37872]: https://hv-eng.atlassian.net/browse/BACKLOG-37872?atlOrigin=eyJpIjoiNWRkNT …
=> [BACKLOG-37872][BACKLOG-38317] Backend Write to VFS location, Create PVFS implementation for RepositoryFileStreamProvider

core/src/main/java/org/pentaho/platform/scheduler2/action/SchedulerOutputPathResolver.java
the file name and parent directory.
=> [BACKLOG-39834] Path building was leaving out a path separator between

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
read properly after being scheduled; the UI treats it as a special case.
=> [BACKLOG-39916] Daily recurrence once per day using DST was not being

ui/src/main/java/org/pentaho/mantle/client/workspace/JsJob.java, ui/src/test/java/org/pentaho/mantle/client/workspace/JsJobTest.java
There are two small changes in behavior here:
- in `getScheduledExtn()`, we now fall through to `-` instead of `report` if the extension is unknown
- the parsing in `getOutputPath()` is a bit more robust and doesn't have issues with input paths that contain a `:` that comes before a `=`
=> [CLEANUP][TEST] Refactor JsJob and add unit tests

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/services/ISchedulerServicePlugin.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
Depends on
https://github.com/pentaho/pentaho-platform/pull/5560
=> Addresses BACKLOG-40051: new endpoint execute schedule permission

api/src/main/java/org/pentaho/platform/api/genericfile/GetTreeOptions.java, api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java, api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java, api/src/test/java/org/pentaho/platform/api/genericfile/IGenericFileServiceTest.java, core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java, core/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java, core/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java, core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java, core/src/test/java/org/pentaho/platform/genericfile/DefaultGenericFileServiceTest.java, ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
Issue: https://hv-eng.atlassian.net/browse/BACKLOG-40086
To be merged with:
- https://github.com/pentaho/pentaho-platform/pull/5562
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/191
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1028
--
- Add treeFilter TreeOption
- Default treeFilter to ALL if not found
- Throw Exception for invalid treeFilter value
- Enable hyperlinkage for VFS Connection locations to Browse Perspective from Scheduler Perspective
- Where operations that only considered folders will now also consider files, changed methods/variables/endpoints/comments accordingly
=> [BACKLOG-40086] Schedule Output Perspective : Allow user to browse Scheduled contents from a VFS location folder

core/pom.xml, ui/pom.xml
mockito further because the gwtmockito package seems to break with anything later than 4.0.0.  This could be a liability in the future.
=> [BACKLOG-40633] Updates for unit tests to run on JDK17. Not upgrading

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/OutputLocationUtils.java, ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
- URL encode the path passed to /folders endpoint
- URL encode the path passed to the session-variable in the schedules panel
PR Set:
1. https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1034
2. https://github.com/pentaho/pentaho-platform/pull/5593
3. https://github.com/pentaho/pentaho-scheduler-plugin/pull/169
=> [BACKLOG-40489] Error when accessing browse files with a user with special characters

api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java, api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java, api/src/main/java/org/pentaho/platform/api/genericfile/model/IGenericFileContentWrapper.java, api/src/test/java/org/pentaho/platform/api/genericfile/IGenericFileServiceTest.java, core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java, core/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java, core/src/main/java/org/pentaho/platform/genericfile/model/DefaultGenericFileContentWrapper.java, core/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java, core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java
PR Set:
1. https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1039
2. https://github.com/pentaho/pentaho-platform/pull/5616
3. https://github.com/pentaho/pentaho-scheduler-plugin/pull/178
4. https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/243
- Introduce new `{path : .+}/content` endpoint to support the opening of PVFS files
- added wrapper class to pass a file's content as InputStream, along with it's name and MIME type, much like FileService.RepositoryFileToStreamWrapper
- heavily borrowed from `FileResource.buildOkResponse( FileService.RepositoryFileToStreamWrapper wrapper )`
=> [BACKLOG-40475] Browse Perspective: "Open" PVFS file actions

api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java, api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java
- Took the chance to fix some doclets regarding this condition.
PR set:
- https://github.com/pentaho/pdi-plugins-ee/pull/1160
/cc @pentaho/hoth
=> [BACKLOG-40356] Fixed HTTP status code returned by Generic File  Subtree endpoint for not found/invalid base path

api/src/main/java/org/pentaho/platform/api/genericfile/model/IGenericFile.java
Added IGenericFIle#getNameDecoded()
PR Set:
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1042
https://github.com/pentaho/pentaho-platform/pull/5652
https://github.com/pentaho/pentaho-scheduler-plugin/pull/187
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/256
=> [BACKLOG-41091] Use Decoded File Name and Title Values in Scheduler Perspective + Browse Perspective missed case

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
1. The set of the new trigger date was not working for other implementation of `Trigger`, like `CalendarIntervalTriggerImpl`
2. Due to the `rescheduleJob()` call a duplicated job was always being triggered when the quartz MisfireHandler would run (every 60 seconds). To prevent this, the misfire instruction of the trigger needs to be set to `MISFIRE_INSTRUCTION_DO_NOTHING`
@pentaho/tatooine_dev please review
=> [BISERVER-15101] Prevent double trigger on triggerNow() execution

core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java, core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java
When the `expandedPath` is set, it will have its children expanded with the same depth as set in `maxDepth`.
This was needed to satisfy the PD mocks for the Browse Files plugin in the pentaho-app-shell project.
=> feat: add children with same depth to expanded path [BACKLOG-41878]

core/pom.xml
was getting a build issue in my IDE due to 
```
<dependency>
<groupId>org.osgi</groupId>
<artifactId>osgi.core</artifactId>
<scope>test</scope>
</dependency>
```
not having a version for the test dependency. 
this version comes from https://github.com/pentaho/maven-parent-poms/blob/56f12d84d2fe4e2831171d44e150488fdfa5a2b1/pom.xml#L77C6-L77C23
=> [CLEANUP] adding vesion to org.osgi:osgi.core test

api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java, api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java, api/src/main/java/org/pentaho/platform/api/genericfile/exception/NotFoundException.java, api/src/main/java/org/pentaho/platform/api/genericfile/exception/OperationFailedException.java, api/src/main/java/org/pentaho/platform/api/genericfile/model/IGenericFileContentWrapper.java, api/src/test/java/org/pentaho/platform/api/genericfile/IGenericFileServiceTest.java, core/pom.xml, core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java, core/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java, core/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java, core/src/main/java/org/pentaho/platform/genericfile/providers/repository/model/RepositoryFile.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java, core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java, core/src/test/java/org/pentaho/platform/genericfile/DefaultGenericFileServiceTest.java, core/src/test/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProviderTest.java
- added corresponding endpoint `GET /plugin/scheduler-plugin/api/generic-files/{id}`
- added missing `getFileContentWrapper` overload for a string path
- fixed documentation of `getFileContentWrapper`
- fixed `getFileContentWrapper` not throwing `NotFoundException`
- fixed repository provider returning wrong name and capabilities for subtree root folders on `getTree` (would return those of the repository root)
- fixed repository files proper having a null type property
- changed to using repository web service's own `DateAdapter` class instead of duplicating code to convert dates back to `Date`
Issue: https://hv-eng.atlassian.net/browse/BACKLOG-42892
@pentaho/millenniumfalcon, please review.
To be merged with:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/289
=> feat: getFile method for generic file service [BACKLOG-42892]

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/NewScheduleDialog.java, ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java, ui/src/main/java/org/pentaho/mantle/client/workspace/JsJob.java, ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java, ui/src/main/java/org/pentaho/mantle/client/workspace/dialogs/ExecuteAvailable.java, ui/src/main/java/org/pentaho/mantle/client/workspace/dialogs/PermissionDenied.java, ui/src/test/java/org/pentaho/mantle/client/workspace/JsJobTest.java
This allows the UI to parse the "ActionAdapterQuartzJob-StreamProvider" parameter with either supported format for retrocompatibility:
- "input file = /some_valid_value:**outputFile =** /another_valid_value"
- "input file = /some_valid_value:**output file=**/another_valid_value"
@pentaho/tatooine_dev please review
=> fix: StringIndexOutOfBoundsException displaying schedules with many variables on them

core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java, generic-file-system/api/src/main/java/org/pentaho/platform/api/genericfile/GetTreeOptions.java, generic-file-system/api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java, generic-file-system/api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java, generic-file-system/api/src/test/java/org/pentaho/platform/api/genericfile/GetTreeOptionsTest.java, generic-file-system/api/src/test/java/org/pentaho/platform/api/genericfile/IGenericFileServiceTest.java, generic-file-system/impl/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java, generic-file-system/impl/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java, generic-file-system/impl/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java, generic-file-system/impl/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java, generic-file-system/impl/src/test/java/org/pentaho/platform/genericfile/DefaultGenericFileServiceTest.java, generic-file-system/impl/src/test/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProviderTest.java
- Added support for `GetTreeOptions#getMaxDepth` of 0
- Added support for `GetTreeOptions#getExpandedMaxDepth`, allowing for a separate depth for the main tree and the expanded paths
- Added support for `GetTreeOptions#isBypassCache` for `getTree` operation
- Changed repository root's name to match the path, and title to have the localized text (important for expand path child search).
- Renamed `GetTreeOptions#showHiddenFiles` to `includeHidden`
- Fixed `GetTreeOptions#equals` and `hashCode`, not including `showHiddenFiles`
- Added missing `GetTreeOptions` tests
PR set:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/296
/cc @pentaho/millenniumfalcon
=> feat: added IGenericFileService getRootTrees method [BACKLOG-42892]

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> fix: Schedule a Report - Execute Now after Report is Run for the first time and in the next minute - Reports are generated twice

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
The check for whether the Next/Finish button could be enabled was happening before the time zone picker list was getting populated. Fix is to directly invoke the change handler callback after the list gets populated to update the button state.
=> [BACKLOG-42985] Fixing a race condition in the UI on initialization.

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
This PR is a backport of https://github.com/pentaho/pentaho-scheduler-plugin/pull/283 to address the bug [BISERVER-15156](https://hv-eng.atlassian.net/browse/BISERVER-15156)  in 10.2.0.3.
@pentaho/tatooine_dev 
[BISERVER-15156]: https://hv-eng.atlassian.net/browse/BISERVER-15156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat[SP-6822]: remove "last run" update on "execute now" (#283)

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, core/src/test/java/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java, ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulerUiUtil.java
⚠️ **Please do not squash and merge this PR** ⚠️ 
Goal:
--
This pull request reintroduces the functionality to update a job's "last run" column in the Scheduler's UI, when a manual trigger (`triggerNow()`) is invoked. It achieves this by utilizing the `previousTriggerNow` property in the JobDataMap. This feature had been previously removed, in https://github.com/pentaho/pentaho-scheduler-plugin/pull/283, because the previous implementation was causing duplicate executions.
To help in the review, I split the implementation into 3 separate PRs:
- [chore: sonar fixes and increased coverage](https://github.com/pentaho/pentaho-scheduler-plugin/pull/295/commits/9006390b2c85217c61260feee21b79392ef3a749)
- [feat: reintroduce last run update on manual …
=> feat: reintroduce last run update on manual trigger

.gitignore, core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, core/src/test/java/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java
Fixes the implementation in https://github.com/pentaho/pentaho-scheduler-plugin/pull/295, as part of **BISERVER-15161**
This PR fixes a bug where the "Last Run" column in the schedule report UI was not updated after clicking the "Execute Now" button for a scheduled report. The fix ensures that the last execution time is properly updated while avoiding duplicate executions.
---
This behavior was initially implemented as part of **BISERVER-15156** to prevent duplicate executions when using "Execute Now" on recurring schedules. However, this temporary solution caused the "Last Run" column to remain outdated.
---
1. **Thread Safety**:
- Introduced a `ReentrantReadWriteLock` to ensure safe access to `JobDetail` and related operations.
2. **Last Run Update**:
- Refactored the `triggerNow` logic …
=> fix: Update Last Run on manual trigger without duplicate executions

core/src/main/java/org/pentaho/platform/web/http/api/resources/ComplexJobTriggerProxy.java
[BACKLOG-44133]-API Response Does Not Match Expected Permissions Format
[BACKLOG-44133]: https://hv-eng.atlassian.net/browse/BACKLOG-44133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44133]-API Response Does Not Match Expected Permissions Format

core/src/main/java/org/pentaho/platform/web/http/api/proxies/BlockStatusProxy.java
[BACKLOG-44169]-Blockout Status API response returns boolean value where string is expected
[BACKLOG-44169]: https://hv-eng.atlassian.net/browse/BACKLOG-44169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44169]-Blockout Status API response returns boolean value where string is expected

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
Main change:
- When `UI_PASS_PARAM` is missing in `configureSimpleTrigger`, we default it to `DAILY` so that old schedules that are missing this parameter can still be imported;
Other changes:
- Made the `logger` variable static in order to call it from static methods + to align with best practices
- Refactored `calculateTriggerInterval()` to make it more coherent with `determineIntervalUnit()`:
- Turned it into a switch instead of an else-if;
- Added an exception for when the `UI_PASS_PARAM` value is missing or invalid, instead of returning `0` and the import failing later with a less comprehensive error message.
=> fix[BISERVER-15276]: add default UI_PASS_PARAM to allow the import of some schedules exported in 9.x

core/src/main/java/org/pentaho/platform/api/scheduler2/ComplexJobTrigger.java
[BACKLOG-44147]-Schedule Job API fails schema validation due to missing @type and incorrect field types
[BACKLOG-44147]: https://hv-eng.atlassian.net/browse/BACKLOG-44147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44147]-Schedule Job API fails schema validation due to missing @type and incorrect field types

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
`UI_PASS_PARAM` `DAILY` was incorrectly dividing the `REPEAT_INTERVAL` values coming from 9.x, as they are expressed in seconds. For that reason, changed the default `UI_PASS_PARAM` (used when it is missing during import, for example for 9.x-exported schedules) to `SECONDS`.
=> fix[BISERVER-15276]: change the default UI_PASS_PARAM to SECONDS for correct interpretation of Repeat Intervals coming from 9.x

core/src/main/java/org/pentaho/platform/web/http/api/resources/JobsResponse.java, core/src/main/java/org/pentaho/platform/web/http/api/resources/JobsResponseEntry.java, core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java
[BACKLOG-45013]-Invalid JSON Map response instead of "Schedule removed successfully"
[BACKLOG-45013]: https://hv-eng.atlassian.net/browse/BACKLOG-45013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-45013]-Invalid JSON Map response instead of "Schedule removed successfully"

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceIntegrationTest.java
removed by the quartz scheduler after they execute. End date is set for 1 hour after the scheduled execution time and repeat interval is 2
years.
=> [BISERVER-15303] Restored missing logic to ensure run once jobs get
