pentaho/pentaho-scheduler-plugin

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleHelper.java
ui/src/main/java/org/pentaho/mantle/client/external/services/PerspectiveManagerUtils.java
ui/src/main/java/org/pentaho/mantle/client/external/services/definitions/IPerspectiveManagerUtils.java
ui/src/main/java/org/pentaho/mantle/client/solutionbrowser/ScheduleCallback.java

/cc @pentaho/hoth. @pentaho/r2d2, @pentaho/millenniumfalcon
To be merged with: https://github.com/pentaho/pentaho-platform/pull/5458

[BACKLOG-37872] Fixed not being able to use OBF or SuperDevMode mode

---

core/pom.xml

it was decided that comment was obsolete via this slack conversation: https://hitachivantara-eng.slack.com/archives/C05BEAC5KHQ/p1701952755412459

[CLEAUP] removing obsolete comments

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java

fix(backend): NullPointer in updateJob expection [BACKLOG-37841]

---

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/NewScheduleDialog.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java

Added classes to NewScheduleDialog elements to aid in automation tests
Related PR:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/108

chore(automation): Add classes to dialog elements [BACKLOG-37841]

---

core/pom.xml
core/src/main/java/org/pentaho/platform/scheduler2/action/DefaultActionInvoker.java
core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
core/src/test/java/org/pentaho/platform/scheduler2/action/ActionRunnerTest.java
core/src/test/java/org/pentaho/platform/scheduler2/action/DefaultActionInvokerTest.java
core/src/test/java/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java
core/src/test/java/org/pentaho/platform/scheduler2/ws/test/DefaultSchedulerServiceTest.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailDialog.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java

to report better error messages when scheduling some types of recurrences.

[BACKLOG-39527] Added exception handling to simple job trigger creation

---

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/NewScheduleDialog.java

this was a regression introduced when the 'static' modifier was removed from 'scheduleLocationTextBox', and the dialog no longer kept the latest location selected when the dialog is reopened.
@pentaho/millenniumfalcon @dcleao please review.

fix: Schedule location value in NewScheduleDialog [BACKLOG-37841]

---

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java

comparing the day of the week.

[BACKLOG-39505] Comparing the calendar date works way better than

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/EmbeddedQuartzSystemListener.java

Reverts pentaho/pentaho-scheduler-plugin#93

Revert "[BACKLOG-39783] - Fix so that the EmbeddedQuartzSystemListener will k…"

---

core/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java

[BACKLOG-39937] Fixing merge cleanup problems; pause job was pausing the

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

Addresses BACKLOG-40117: fix error hover schedule table with pagination

---

assembly/pom.xml
pom.xml

feat: create profile to unzip assembly to local biserver [BACKLOG-40194]

---

ui/src/main/java/org/pentaho/mantle/client/workspace/CellTable.css
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

feat: Disable select all on empty list [BACKLOG-39987]

---

ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages.properties

feat: Capitalize parameter column [BACKLOG-39987]

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

feat: select by clicking on the listed item-out checkbox [BACKLOG-39987]

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulerUiUtil.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
ui/src/test/java/org/pentaho/mantle/client/workspace/SchedulerUiUtilTest.java

Addresses BACKLOG-39987: fix some schedules table issues

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/ISchedulerServicePlugin.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java

Addresses BACKLOG-40072: Viewing All Schedules (backend)

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

Addresses BACKLOG-40048: Viewing All Schedules (frontend)

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

Addresses BACKLOG-40050: Pause and resume schedules

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPerspectivePanel.java

Addresses BACKLOG-40051: fix admin permissions

---

ui/src/main/java/org/pentaho/mantle/client/workspace/BlockoutPanel.java

Addresses BACKLOG-40344: Blockout schedule left align of toolbox

---

api/src/main/java/org/pentaho/platform/api/genericfile/GetTreeOptions.java
core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java
core/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java
core/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java
core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java
core/src/test/java/org/pentaho/platform/genericfile/DefaultGenericFileServiceTest.java
core/src/test/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProviderTest.java

- Plus some renames, and small refactorings to support testing.
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/210

[BACKLOG-39254] Added tests for BaseGenericFileProvider and RepositoryFileProvider

---

api/src/main/java/org/pentaho/platform/api/genericfile/GenericFilePermission.java
api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileProvider.java
api/src/main/java/org/pentaho/platform/api/genericfile/IGenericFileService.java
api/src/main/java/org/pentaho/platform/api/genericfile/exception/InvalidOperationException.java
api/src/main/java/org/pentaho/platform/api/genericfile/exception/NotFoundException.java
api/src/test/java/org/pentaho/platform/api/genericfile/IGenericFileServiceTest.java
core/src/main/java/org/pentaho/platform/genericfile/DefaultGenericFileService.java
core/src/main/java/org/pentaho/platform/genericfile/providers/repository/RepositoryFileProvider.java
core/src/main/java/org/pentaho/platform/scheduler2/action/SchedulerOutputPathResolver.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
core/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolverTest.java

@pentaho/hoth Please review.
To be merged before https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/236

[BACKLOG-40063] [BACKLOG-40302] - Enhance Generic File Service to control access to VFS connections' folders

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
ui/src/main/java/org/pentaho/mantle/client/workspace/dialogs/ExecuteAvailable.java
ui/src/main/java/org/pentaho/mantle/client/workspace/dialogs/PermissionDenied.java
ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages.properties
ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages_en.properties

Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1036

feat: update no permissions dialog on trigger now [BACKLOG-40514]

---

core/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java

This PR is part of https://github.com/pentaho/pentaho-platform/pull/5609

[BACKLOG-40444] Browse Perspective: Improve folder tree model depth variable and related API call

---

ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages.properties
ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages_en.properties

Related PR:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/239

chore: review execute schedule dialogs i18n [BACKLOG-40514]

---

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidator.java

[BISERVER-14898] - Remove Deprecated Version of StringUtils

---

ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[BACKLOG-41343] Remove param preview link for users without edit permissons

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java

[BACKLOG-41338] Execute Now does not work after first normal timely execution of the created schedule

---

core/pom.xml

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

---

core/src/main/java/org/pentaho/platform/api/scheduler2/ComplexJobTrigger.java
core/src/main/java/org/pentaho/platform/api/scheduler2/JobTrigger.java
core/src/main/java/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtil.java
core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/ComplexJobTriggerProxy.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
core/src/test/java/org/pentaho/platform/scheduler2/quartz/test/ComplexTriggerTest.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidator.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/ScheduleEditorValidator.java
ui/src/main/java/org/pentaho/mantle/client/workspace/JsJobTrigger.java
ui/src/test/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidatorTest.java

Reverts pentaho/pentaho-scheduler-plugin#201

Revert "[BISERVER-14374] PUC UI now allows users to set the time zone of a"

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/ISchedulerServicePlugin.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleHelper.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPerspectivePanel.java

Reverts pentaho/pentaho-scheduler-plugin#208

Revert "[BISERVER-15051] hide internal variables PUC side"

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/ISchedulerServicePlugin.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleHelper.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPerspectivePanel.java

Reverts pentaho/pentaho-scheduler-plugin#210

Revert "Revert "[BISERVER-15051] hide internal variables PUC side""

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
core/src/test/java/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJobTest.java

[BISERVER-14374] Bug fix; start time field is null for cron jobs (not

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java

[BISERVER-14374] Ensure trigger end date hours and minutes are handled,

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/CronEditor.java
ui/src/test/java/org/pentaho/mantle/client/dialogs/scheduling/CronEditorTest.java

[BACKLOG-43017] Cron trigger start time was not getting passed through

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/GenericFileResource.java
generic-file-system/api/src/main/java/org/pentaho/platform/api/genericfile/GenericFilePath.java
generic-file-system/api/src/main/java/org/pentaho/platform/api/genericfile/GetTreeOptions.java
generic-file-system/api/src/test/java/org/pentaho/platform/api/genericfile/GetTreeOptionsTest.java
generic-file-system/impl/src/main/java/org/pentaho/platform/genericfile/BaseGenericFileProvider.java
generic-file-system/impl/src/test/java/org/pentaho/platform/genericfile/BaseGenericFileProviderTest.java

- Fix expandedMaxDepth missing from equals and hashCode, resulting in some random results
@pentaho/millenniumfalcon, please review.

feat: added support multiple expanded paths [BACKLOG-42892]

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolverTest.java

Worked with @dcleao and @nawaz34-hitachivantara to address the fact that schedules were failing to import due to user roles/permissions, and output path validation for different importing user vs schedule user and vfs:
- Made sure to be getting the user from the schedule request, not the session
- Use the schedule request user for output path validation via runAs
- Refactored and updated UT coverage

[BACKLOG-43001] [BISERVER-15167] [BISERVER-15168] Restoring schedules from previous and current version

---

ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/CronEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
ui/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java

Change the default for "gathering metrics" to 'false'.
Remove the section for additional options.
@pentaho/tatooine_dev

[BISERVER-15179] Revision required for Details Section of New Schedule Dialog on Scheduler Plugin

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java

@pentaho/tatooine_dev please review

fix: Fix possible NPE

---

core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolverTest.java

Schedules are lost during Backup-restore procedure even when restore is successful on same version of Pentaho Server (10.2 Suite)
Restored schedules from previous versions are missing on latest scheduler-plugin (10.2 Suite)
Worked with @dcleao and @nawaz34-hitachivantara to address the fact that schedules were failing to import due to user roles/permissions, and output path validation for different importing user vs schedule user and vfs. So for this repo we:
Made sure to be getting the user from the schedule request, not the session
Use the schedule request user for output path validation via runAs
Refactored and updated UT coverage:
We are now testing on resolveOutputFilePathCore because the original method uses SecurityHelper.getInstance().runAsUser( getScheduleOwner(), …

[SP-6750] [SP-6751] Backport of BISERVER-15167, BISERVER-15168:

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
core/src/test/java/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java

as the start date. It should now be converted between the PUC server's time zone and the time zone specified in the Spoon UI correctly.

[BISERVER-15241] End date of jobs was not getting handled the same way

---

assembly/src/main/plugin.ws.spring.xml
core/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java
core/src/main/java/org/pentaho/platform/scheduler2/ws/ISchedulerService.java
pom.xml

[BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration
[BACKLOG-43612]: https://hv-eng.atlassian.net/browse/BACKLOG-43612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration

---

core/src/main/java/org/pentaho/platform/api/scheduler2/SimpleJobTrigger.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java

[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE

---

core/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java

This PR removes the functionality of updating the "Last Run" field when a manual "Execute Now" is triggered.
The intent of this is to fix the underlying problems that this update has been causing in the scheduler for the past year.
See:
- [BACKLOG-41338](https://hv-eng.atlassian.net/browse/BACKLOG-41338)
- [BISERVER-14971](https://hv-eng.atlassian.net/browse/BISERVER-14971)
- [BISERVER-15101](https://hv-eng.atlassian.net/browse/BISERVER-15101)
- [BISERVER-15161](https://hv-eng.atlassian.net/browse/BISERVER-15161)
- [BISERVER-15156](https://hv-eng.atlassian.net/browse/BISERVER-15156) (current work)
[BACKLOG-41338]: https://hv-eng.atlassian.net/browse/BACKLOG-41338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BISERVER-14971]: …

feat: remove "last run" update on "execute now"

---

core/src/it/java/org/pentaho/platform/web/http/api/resources/JobScheduleRequestJaxbIT.java

[BACKLOG-41693]-Fix all the broken testcases in pentaho scheduler-plugin
[BACKLOG-41693]: https://hv-eng.atlassian.net/browse/BACKLOG-41693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41693]-Fix all the broken testcases in pentaho scheduler-plugin

---

assembly/src/main/settings.xml
core/src/main/java/org/pentaho/platform/scheduler2/action/SchedulerOutputPathResolver.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java
core/src/main/resources/org/pentaho/platform/scheduler2/messsages/messages.properties
core/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolverTest.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java

This commit reverts below commits : 
e8fa8b2c2e934aab62e0eff6c61093b7592e7653
9f3c45468581ec12434d07f0ad316726fa18a348
34c04f0d8bbfd62652d8dd319323cd8260d1c304

Reverts of [SP-6823] Backport of BISERVER-15261, [SP-6823] Backport of BISERVER-15263, [SP-6823] Backport of BISERVER-15264

---

core/src/main/java/org/pentaho/platform/api/scheduler2/JobWrapper.java
core/src/main/java/org/pentaho/platform/api/scheduler2/jackson/DateDeserializer.java
core/src/main/java/org/pentaho/platform/api/scheduler2/jackson/DateSerializer.java

[BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat
[BACKLOG-44915]: https://hv-eng.atlassian.net/browse/BACKLOG-44915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat

---

assembly/src/main/plugin.spring.xml
core/src/main/java/org/pentaho/platform/scheduler2/action/SchedulerOutputPathResolver.java
core/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
core/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceIntegrationTest.java

To be merged with: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/395

fix: use local generic-file-service for imports [PPUC-124]
